services:
  - type: web
    name: telegram-video-bot
    # Tell Render to use Docker instead of Python
    env: docker
    plan: free
    # Dockerfile path is automatically detected
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DUMP_CHANNEL_ID
        sync: false