services:
  - type: web
    name: telegram-video-bot
    env: python
    plan: free # Or your desired plan
    buildCommand: |
      pip install -r requirements.txt
      apt-get update && apt-get install -y ffmpeg
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6 # Or your preferred Python version
      - key: BOT_TOKEN
        sync: false # Set this in the Render dashboard
      - key: DUMP_CHANNEL_ID
        sync: false # Set this in the Render dashboard
      - key: RENDER_APP_NAME
        fromService:
          type: web
          name: telegram-video-bot # Must match the 'name' field above
