services:
  - type: web
    name: telegram-video-bot
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      apt-get update && apt-get install -y ffmpeg
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6
      - key: BOT_TOKEN
        sync: false # Set this in the Render dashboard
      - key: DUMP_CHANNEL_ID
        sync: false # Set this in the Render dashboard
      - key: RENDER_APP_NAME # This key gets its value from the service itself
        fromService:
          type: web
          name: telegram-video-bot # Must match the 'name' field on line 3
          property: name # We want the 'name' property of the service