services:
  - type: web
    name: telegram-video-bot
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      sudo apt-get update && sudo apt-get install -y ffmpeg # <-- Added sudo here
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6
      - key: BOT_TOKEN
        sync: false
      - key: DUMP_CHANNEL_ID
        sync: false